orbslam3:
  ros__parameters:
    world_frame: "map"
    odom_frame: "odom"
    camera_optical_frame: "zedx_left_camera_optical_frame"
    body_frame: "base_link"
    body_optical_frame: "zedx_imu_optical_frame"
    # camera_optical_frame: "d455_infra1_optical_frame"
    # body_frame: "d455_link"
    # body_optical_frame: "d455_imu_optical_frame"